# Generated by Django 4.0.4 on 2023-05-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default='sample', max_length=100),
        ),
    ]
